tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container":         "#f2ecf0",
        "surface-container-low":     "#f8f2f5",
        "surface-container-high":    "#ede6eb",
        "surface-container-highest": "#e7e0e6",
        "surface-container-lowest":  "#ffffff",
        "surface":                   "#fef8fb",
        "surface-variant":           "#e7e0e6",
        "surface-dim":               "#dfd8de",
        "surface-bright":            "#fef8fb",
        "surface-tint":              "#952cb1",
        "on-surface":                "#343136",
        "on-surface-variant":        "#625e62",
        "on-background":             "#343136",
        "background":                "#fef8fb",
        "outline":                   "#7e797e",
        "outline-variant":           "#b6b0b5",
        "inverse-surface":           "#0f0e10",
        "inverse-on-surface":        "#a09c9e",
        "primary":                   "#952cb1",
        "primary-dim":               "#871ba4",
        "primary-fixed":             "#f1a6ff",
        "primary-fixed-dim":         "#ec91ff",
        "primary-container":         "#f1a6ff",
        "on-primary":                "#fff7fb",
        "on-primary-container":      "#680082",
        "on-primary-fixed":          "#47005a",
        "on-primary-fixed-variant":  "#760093",
        "inverse-primary":           "#e67aff",
        "secondary":                 "#ac2d5e",
        "secondary-dim":             "#9c1f52",
        "secondary-fixed":           "#ffd9e1",
        "secondary-fixed-dim":       "#ffc5d3",
        "secondary-container":       "#ffd9e1",
        "on-secondary":              "#fff7f7",
        "on-secondary-container":    "#9a1d50",
        "on-secondary-fixed":        "#81013e",
        "on-secondary-fixed-variant":"#a7295a",
        "tertiary":                  "#6948c1",
        "tertiary-dim":              "#5c3ab4",
        "tertiary-fixed":            "#c2acff",
        "tertiary-fixed-dim":        "#b59cff",
        "tertiary-container":        "#c2acff",
        "on-tertiary":               "#fdf7ff",
        "on-tertiary-container":     "#3f1496",
        "on-tertiary-fixed":         "#27006a",
        "on-tertiary-fixed-variant": "#48229f",
        "error":                     "#ac3149",
        "error-dim":                 "#770326",
        "error-container":           "#f76a80",
        "on-error":                  "#fff7f7",
        "on-error-container":        "#68001f",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body":     ["Plus Jakarta Sans", "sans-serif"],
        "label":    ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg":      "0.5rem",
        "xl":      "0.75rem",
        "2xl":     "1rem",
        "3xl":     "1.5rem",
        "full":    "9999px",
      },
    },
  },
};
